# config/paths.py
from pathlib import Path
import matplotlib as mpl

# Project root
BASE_DIR = Path(__file__).resolve().parent.parent

# Config
CONFIG_DIR = BASE_DIR / 'config'

# Data
DATA_DIR       = BASE_DIR / 'data'
PP_DATA_DIR    = DATA_DIR / 'pp_data'
QUEST_RESP_PP = PP_DATA_DIR / 'quest_resp_events_merged_pp.csv'
QUEST_RESP_ALL_TARGETS_TRASNF_PP = PP_DATA_DIR / 'quest_resp_events_merged_targets_transformed_pp.csv'
QUEST_PCA_REDUCED = PP_DATA_DIR / 'quest_pca_reduced.csv'
QUEST_PCA_REDUCED_TARGETS_TRASNF_PP = PP_DATA_DIR / 'quest_pca_reduced_targets_transformed.csv'  # best_targets_for_subjective_data.py
RAW_DATA_DIR   = DATA_DIR / 'raw_data'

# Other top‐level folders
LIBRARY_DIR    = BASE_DIR / 'library'
NOTEBOOK_DIR   = BASE_DIR / 'notebook'
RESULTS_DIR    = BASE_DIR / 'results'

# Source
SRC_DIR              = BASE_DIR / 'src'
PRE_PROCESS_PY       = SRC_DIR  / 'pre_process.py'
STAT_TEST_PY         = SRC_DIR  / 'stat_test.py'
VISUALIZATION_PY     = SRC_DIR  / 'visualization.py'

# Now bundle into a nested dict
config = {
    'base_dir': BASE_DIR,
    'config': {
        'root': CONFIG_DIR,
    },
    'data': {
        'root': DATA_DIR,
        'pp_data': {
            'dir':    PP_DATA_DIR,
            'q_resp': QUEST_RESP_PP,
            'pca_reduced': QUEST_PCA_REDUCED,
            'q_resp_trasnf': QUEST_RESP_ALL_TARGETS_TRASNF_PP,  # targets transformation
            'pca_reduced_transf': QUEST_PCA_REDUCED_TARGETS_TRASNF_PP  # targets transformations

        },
        'raw_data': {
            'dir': RAW_DATA_DIR,
            'q_resp': RAW_DATA_DIR.joinpath('quest_resp_events_merged.csv'),
        },
        'encodings': DATA_DIR.joinpath('ordinal_encoding.pickle'),
    },
    'library':  LIBRARY_DIR,
    'notebook': NOTEBOOK_DIR,
    'results':  {
        'dir': RESULTS_DIR,
        'within_stats': RESULTS_DIR.joinpath('within_stats'),
        'stat_tests': RESULTS_DIR.joinpath('stat_tests'),
        'post_sleep_stats': RESULTS_DIR.joinpath('post_sleep_stats'),
        'best_target': RESULTS_DIR.joinpath('best_target'),
    },
    'src': {
        'root':            SRC_DIR,
        'pre_process_py':  PRE_PROCESS_PY,
        'stat_test_py':    STAT_TEST_PY,
        'visualization_py':VISUALIZATION_PY,
    }
}
# %% plots

# ---- Global default styling for all plots ----
mpl.rcParams.update({
    'font.size'           : 18,  # Base font size
    'axes.titlesize'      : 20,  # Axes title
    'axes.labelsize'      : 18,  # X/Y axis labels
    'xtick.labelsize'     : 16,  # X tick labels
    'ytick.labelsize'     : 16,  # Y tick labels
    'legend.title_fontsize': 18, # Legend title
    'legend.fontsize'     : 16   # Legend entries
})


# %% Dictionary to encode the responses
# encoder_dict = {
#     'gender': {
#         'Male': 1,
#         'Female': 0},
#     'race': {
#         'White (Caucasian)': 0,
#         'African American': 1,
#         'Hispanic': 2,
#         'American Indian': 3,
#         'Pacific Islander': 4,
#         'Asian': 5,
#         'Alaska Native': 6,
#         'Native Hawaiian': 7,
#     },
#
#     'epworth_questionnaire': {
#         'Would never doze': 0,
#         'Slight chance': 1,
#         'Moderate chance': 2,
#         'High chance of dozing': 3
#     },
#
#     'anxiety_questionnaire': {
#         'Not at all / None': 0,
#         'Slight / Few times': 1,
#         'Moderate / Sometimes': 2,
#         'Often': 3,
#         'Severe / Always': 4
#     },
#
#     'refreshed_questionnaire': {
#         'Not at all / None': 0,
#         'A little': 1,
#         'Quite a bit': 2,
#         'Extremely': 3
#     },
#
#     'sleep_quality_questionnaire': {
#         'Less rested': -1,
#         'Same': 0,
#         'More rested than usual': 1
#     },
#
#     'awake_feeling_questionnaire': {
#         'Worse': -1,
#         'Same': 0,
#         'Better': 1
#     }
# }

# %%
metrics_psg = {
    'resp_events': {
        # all the event names you have in your columns
        'event_keywords': [
            'apnea+hyp+rera',
            'apnea+hyp',
            'rdi_with_reras',
            'ahi_no_reras',
            'hi_hypopneas_only',
            'ai_apneas_only',
            'ri_rera_only',
            'rera_5_hyp_with_arousal_without_desaturation',
            'hyp_4_30_airflow_reduction_desaturation',
            'ma',
            'ca',
            'oa'
        ],
        # raw‐count events (we will normalize these by time)
        'raw_events': [
            'oa',
            'ca',
            'ma',
            'hi_hypopneas_only',  # hyponeas
            'ri_rera',  # rera
            'hyp_4_30_airflow_reduction_desaturation',
            'rera_5_hyp_with_arousal_without_desaturation',
            'apnea',
            'apnea+hyp',
            'apnea+hyp+rera'
        ],
        # indices already in “#/hr” (we take these as‐is)
        'indices': [
            'rdi_with_reras',  # RDI (includes reras) Formula: (OA + HYP + RERA) / hrs
            'ahi_no_reras',  # AHI (ahi no reras) Formula: (OA + HYP) / hrs
            'hi_hypopneas_only',  # HI (hypopnea) Formula: HYP / hrs
            'ai_apneas_only',  # AI (apnea) Formula: OA + CA + MA / hrs
            'ri_rera_only'  # RI (rera) Formula: RERA / hrs
        ],
        # the positions you actually have time‐columns for
        'position_keywords': [
            'total','prone','supine','left','right','rem_supine'
        ],
        # if you ever want to split out full REM/NREM times
        'sleep_stage': [
            'rem','nrem'
        ]
    }
}


# %% columns to remove after assing relations and meaningfullness
col_remove = [
    'PreSleep_Medications_Today',

    'Tobacco_Quit',
    'Alcohol_Quit',

    'SA_Sleep_Gasp',
    'SA_Sleep_Other_Movements',
    'SA_Sleep_Leg_Jerk',
    'SA_Sleep_Eat',
    'SA_Sleep_Hunger',
    'SA_Sleep_Heart_Pain',
    'SA_Sleep_Someone_Room',
    'SA_Sleep_SomeOne_Bed',
    'SA_Sleep_Alert',
    'SA_Sleep_Nasal_Medication',
    'SA_Sleep_Asthma',
    'SA_Sleep_Parasthesia',
    'SA_Sleep_Stomach_Pain',
    'HIV',
    'Hernia',

    'EpReading',
    'EpSittingQuietlyInPublicPlace',

    # 'diabetes',
    'Frequent_Cough',

    # 'sa_Falling_Asleep_LegPain',
    'sa_Problem_With_Tiredness',
    'sa_Falling_Asleep_Depressed',
    'sa_Falling_Asleep_Thought',
    'sa_Falling_Asleep_Muscular_Tension',
    'sa_Problem_Going_Tosleep_Atnight',
    'sa_Falling_Asleep_Afraid',
    'sa_Before_Bed_Sleep_Aids',

    'PreSleep_Feel_Sleepy_Now',
    'sa_Problem_With_Sleepiness',
    'sa_Problem_Wakingup_During_Night',

    'PreSleep_Physical_Strenuous_Day',
    'PreSleep_Medications_Today',
    'PreSleep_Caffeinated_Beverage_Today',
    'PreSleep_Feel_Tired_Now',
    'PreSleep_Feel_Sleepy_Now',
    'PreSleep_Feel_Alert_Now',
    'PreSleep_Alcohol_Beverage_Today',

    'StudyType',
    'menopausal_stage',
]

# %%
sections = ["dem_",
            "ep_",
            "mh_",
            "sa_",
            "presleep_",
            "postsleep_",
            "resp"]
# sections = [ "ep_", "mh_", "mh_", "ph3", "sa_", "presleep", "postsleep", "resp"]
# sections = ['', '', 'sa_', 'SA_', 'PreSleep_', 'Ep']  # removed post sleep

# %% column defintions
encoding = dict(
    dem_age={'definition': 'Age',
               'encoding': {}},
    dem_bmi={'definition': 'BMI',
               'encoding': {}},
    dem_gender={'definition': 'gender', 'encoding': {'male': 1, 'female': 0}},
    dem_race={'definition': 'race',
          'encoding': {'white (caucasian)': 0,
                       'african american': 1,
                       'hispanic': 2,
                       'american indian': 3,
                       'pacific islander': 4,
                       'asian': 5,
                       'alaska native': 6,
                       'native hawaiian': 7}},
    ep_reading={'definition': 'Ep.Reading',
                'encoding': {'high chance of dozing': 3, 'moderate chance': 2, "slight chance": 1,
                             'would never doze': 0}},
    ep_watchingtv={'definition': 'Ep.Watching TV',
                'encoding': {'high chance of dozing': 3,
                             'moderate chance': 2,
                             'slight chance': 1,
                             'would never doze': 0}},
    ep_sittingquietlyinpublicplace={'definition': 'Ep.sitting quietly',
                                'encoding': {'high chance of dozing': 3, 'moderate chance': 2, 'slight chance': 1,
                                             'would never doze': 0}},
    ep_carpassenger={'definition': 'Ep.car passenger',
                 'encoding': {'high chance of dozing': 3, 'moderate chance': 2, 'slight chance': 1,
                              'would never doze': 0}},
    ep_lyingdown={'definition': 'Ep.lying down',
                'encoding': {'high chance of dozing': 3,
                             'moderate chance': 2,
                             'slight chance': 1,
                             'would never doze': 0}},
    ep_talking={'definition': 'Ep.talking',
            'encoding': {'high chance of dozing': 3,
                         'moderate chance': 2,
                         'slight chance': 1,
                         'would never doze': 0}},
    ep_sittingquietlyafterlunch={'definition': 'Ep.sitting quietly after lunch',
                             'encoding': {'high chance of dozing': 3,
                                          'moderate chance': 2,
                                          'slight chance': 1,
                                          'would never doze': 0}},
    ep_incar={'definition': 'Ep.in car',
            'encoding': {'high chance of dozing': 3,
                         'moderate chance': 2,
                         'slight chance': 1,
                         'would never doze': 0}},
     ep_score={'definition': 'Ep.Score', 'encoding':{}},

     mh_tuberculosis={'definition': 'tuberculosis',
                      'encoding': {'yes': 1, 'no': 0}},
     mh_intestinal_disease={'definition': 'intestinal_disease',
                            'encoding': {'yes': 1, 'no': 0}},
     mh_cancer={'definition': 'cancer', 'encoding': {'yes': 1, 'no': 0}},
     mh_peptic_ulcer={'definition': 'peptic_ulcer', 'encoding': {'yes': 1, 'no': 0}},
     mh_high_blood_pressure={'definition': 'high_blood_pressure', 'encoding': {'yes': 1, 'no': 0}},
     mh_liver_disease={'definition': 'liver_disease', 'encoding': {'yes': 1, 'no': 0}},
     mh_diabetes={'definition': 'diabetes', 'encoding': {'yes': 1, 'no': 0}},
     mh_seizures={'definition': 'seizures', 'encoding': {'yes': 1, 'no': 0}},
     mh_heart_attack={'definition': 'heart_attack', 'encoding': {'yes': 1, 'no': 0}},
     mh_tobacco_habit={'definition': 'tobacco_habit', 'encoding': {'yes': 1, 'no': 0}},
     mh_other_heart_disease={'definition': 'other_heart_disease', 'encoding': {'yes': 1, 'no': 0}},
     mh_tobacco_quit={'definition': 'tobacco_quit', 'encoding': {'yes': 1, 'no': 0}},
     mh_kidney_disease={'definition': 'kidney_disease', 'encoding': {'yes': 1, 'no': 0}},
     mh_alcohol={'definition': 'alcohol', 'encoding': {'yes': 1, 'no': 0}},
     mh_alcohol_quit={'definition': 'alcohol_quit', 'encoding': {'yes': 1, 'no': 0}},
     mh_thyroid_disease={'definition': 'thyroid_disease', 'encoding': {'yes': 1, 'no': 0}},
     mh_caffeinated_beverage={'definition': 'caffeinated_beverage', 'encoding': {'yes': 1, 'no': 0}},
     mh_stomach_disease={'definition': 'stomach_disease', 'encoding': {'yes': 1, 'no': 0}},
     mh_head_ache={'definition': 'head_ache', 'encoding': {'yes': 1, 'no': 0}},
     mh_frequent_cough={'definition': 'frequent_cough', 'encoding': {'yes': 1, 'no': 0}},
     mh_breathe_difficulty={'definition': 'breathe_difficulty', 'encoding': {'yes': 1, 'no': 0}},
     mh_nasal_discharge={'definition': 'nasal_discharge', 'encoding': {'yes': 1, 'no': 0}},
     mh_painful_sinus={'definition': 'painful_sinus', 'encoding': {'yes': 1, 'no': 0}},
     mh_breath_shortness={'definition': 'breath_shortness', 'encoding': {'yes': 1, 'no': 0}},
     mh_allergy={'definition': 'allergy', 'encoding': {'yes': 1, 'no': 0}},
     mh_dentures={'definition': 'dentures', 'encoding': {'yes': 1, 'no': 0}},
     mh_smothering_spells_at_night={'definition': 'smothering_spells_at_night', 'encoding': {'yes': 1, 'no': 0}},
     mh_legs_swollen={'definition': 'legs_swollen', 'encoding': {'yes': 1, 'no': 0}},
     mh_irregular_heart_beat={'definition': 'irregular_heart_beat', 'encoding': {'yes': 1, 'no': 0}},
     mh_heart_enlarge={'definition': 'heart_enlarge', 'encoding': {'yes': 1, 'no': 0}},
     mh_chest_pain={'definition': 'chest_pain', 'encoding': {'yes': 1, 'no': 0}},
     mh_morethanone_pillow={'definition': 'morethanone_pillow', 'encoding': {'yes': 1, 'no': 0}},
     mh_swallow_difficulty={'definition': 'swallow_difficulty', 'encoding': {'yes': 1, 'no': 0}},
     mh_heartburn={'definition': 'heartburn', 'encoding': {'yes': 1, 'no': 0}},
     mh_voice_changes={'definition': 'voice_changes', 'encoding': {'yes': 1, 'no': 0}},
     mh_hernia={'definition': 'hernia', 'encoding': {'yes': 1, 'no': 0}},
     mh_muscular_pain={'definition': 'muscular_pain', 'encoding': {'yes': 1, 'no': 0}},
     mh_joint_pain={'definition': 'joint_pain', 'encoding': {'yes': 1, 'no': 0}},
     mh_muscle_weakness={'definition': 'muscle_weakness', 'encoding': {'yes': 1, 'no': 0}},
     mh_arthritis={'definition': 'arthritis', 'encoding': {'yes': 1, 'no': 0}},
     mh_thyroid_enlarge={'definition': 'thyroid_enlarge', 'encoding': {'yes': 1, 'no': 0}},
     mh_weight_loss={'definition': 'weight_loss', 'encoding': {'yes': 1, 'no': 0}},
     mh_abnormal_glucose={'definition': 'abnormal_glucose', 'encoding': {'yes': 1, 'no': 0}},
     mh_weight_gain={'definition': 'weight_gain', 'encoding': {'yes': 1, 'no': 0}},
     mh_low_blood_sugar={'definition': 'low_blood_sugar', 'encoding': {'yes': 1, 'no': 0}},
     mh_low_blood_pressure={'definition': 'low_blood_pressure', 'encoding': {'yes': 1, 'no': 0}},
     mh_hiv={'definition': 'hiv', 'encoding': {'yes': 1, 'no': 0}},
     mh_anemia={'definition': 'anemia', 'encoding': {'yes': 1, 'no': 0}},
     mh_personality_changes={'definition': 'personality_changes', 'encoding': {'yes': 1, 'no': 0}},
     mh_stroke_history={'definition': 'stroke_history', 'encoding': {'yes': 1, 'no': 0}},
     mh_depression={'definition': 'depression', 'encoding': {'yes': 1, 'no': 0}},
     mh_memory_loss={'definition': 'memory_loss', 'encoding': {'yes': 1, 'no': 0}},
     mh_sleep_difficulty={'definition': 'sleep_difficulty', 'encoding': {'yes': 1, 'no': 0}},
     mh_body_control_difficulty={'definition': 'body_control_difficulty', 'encoding': {'yes': 1, 'no': 0}},
     mh_paralysis_attacks={'definition': 'paralysis_attacks', 'encoding': {'yes': 1, 'no': 0}},
     mh_body_shake={'definition': 'body_shake', 'encoding': {'yes': 1, 'no': 0}},
     mh_speak_difficulty={'definition': 'speak_difficulty', 'encoding': {'yes': 1, 'no': 0}},
    # feature engineered features
    sa_work_sleep_accidents_div_week={'definition': 'sleep_related_accidents',
                                      'encoding': {}},
    sa_no_of_misses_binary={'definition': 'sleep related misses',
                                      'encoding': {'yes': 1, 'no': 0}},
    sa_sleepiness_affect_performance={'definition': 'sleepiness_performance',
                                      'encoding': {}},

    sa_sleep_get_going={'definition': 'Sleep get going',
                                      'encoding': {}},

     sa_problem_going_tosleep_atnight={'definition': 'Problem going to sleep at night',
                                        'encoding': {'moderate / sometimes': 2, 'not at all / none': 0, 'often': 3,
                                                     'severe / always': 4, 'slight / few times': 1}},
     sa_third_awaken_part={'definition': 'sa_third_awaken_part', 'encoding': {'yes': 1, 'no': 0}},
     sa_problem_wakingup_during_night={'definition': 'Problem waking up during night',
                                        'encoding': {'moderate / sometimes': 2, 
                                                     'not at all / none': 0, 
                                                     'often': 3,
                                                     'severe / always': 4, 
                                                     'slight / few times': 1}},
     sa_falling_asleep_thought={'definition': 'Falling asleep thought',
                                 'encoding': {'moderate / sometimes': 2, 
                                                     'not at all / none': 0, 
                                                     'often': 3,
                                                     'severe / always': 4, 
                                                     'slight / few times': 1}},
     sa_problem_not_feeling_rested={'definition': 'Problem not feeling rested',
                                     'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_falling_asleep_depressed={'definition': 'Falling asleep depressed',
                                   'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_problem_with_tiredness={'definition': 'Problem with tiredness',
                                 'encoding': {'moderate / sometimes': 2, 
                                                     'not at all / none': 0, 
                                                     'often': 3,
                                                     'severe / always': 4, 
                                                     'slight / few times': 1}},
     sa_falling_asleep_worry={'definition': 'Falling asleep worry',
                               'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_problem_with_sleepiness={'definition': 'Problem with sleepiness',
                                  'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_falling_asleep_muscular_tension={'definition': 'Falling asleep muscular tension',
                                          'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_falling_asleep_afraid={'definition': 'Falling asleep afraid',
                                'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_falling_asleep_paralyzed={'definition': 'Falling asleep paralyzed',
                                   'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_before_bed_watch_tv={'definition': 'Bed before watch TV',
                             'encoding': {'yes': 1, 'no': 0}},
     sa_falling_asleep_jerk={'definition': 'Falling asleep jerk',
                              'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_before_bed_sleep_aids={'definition': 'Before bed slee aid',
                               'encoding': {'yes': 1, 'no': 0}},
     sa_falling_asleep_legpain={'definition': 'anxiety_questionnaire',
                                 'encoding': {'moderate / sometimes': 2, 
                                                     'not at all / none': 0, 
                                                     'often': 3,
                                                     'severe / always': 4, 
                                                     'slight / few times': 1}},
     sa_first_awaken_part={'definition': 'First awaken part',
                           'encoding': {'yes': 1, 'no': 0}},
     sa_falling_asleep_dream={'definition': 'Falling asleep dream',
                               'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_second_awaken_part={'definition': 'Second awaken part',
                            'encoding': {'yes': 1, 'no': 0}},
     sa_falling_asleep_discomfort={'definition': 'Falling asleep discomfort',
                                    'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_someone_room={'definition': 'Sleep someone room',
                            'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_gasp={'definition': 'Sleep gaps',
                    'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_someone_bed={'definition': 'Sleep someone bed',
                              'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_choke={'definition': 'Sleep choke',
                     'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_special_surface={'definition': 'Sleep special surface',
                               'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_breath_problem={'definition': 'Sleep breath problem',
                              'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_restless={'definition': 'Sleep restless',
                        'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_sweat={'definition': 'Sleep sweat',
                     'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_disturb_partner={'definition': 'Sleep disturb partner',
                               'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_walk={'definition': 'Sleep walk',
                    'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_provide_assistance={'definition': 'Sleep provide assistance',
                                  'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_talk={'definition': 'Sleep talk',
                    'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_nasal_congestion={'definition': 'Sleep nasal congestion',
                                'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_grind_teeth={'definition': 'Grind teeth',
                           'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_nasal_medication={'definition': 'Nasal medication',
                                'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_leg_jerk={'definition': 'Leg jerk',
                        'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_snore={'definition': 'Sleep snore',
                     'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_other_movements={'definition': 'Sleep other movements',
                               'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_stop_breath={'definition': 'Stop breath',
                           'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_eat={'definition': 'Sleep eat',
                   'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_stomach_pain={'definition': 'Sleep somatch pain',
                              'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_thirst={'definition': 'Sleep thirst',
                      'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_leg_cramps={'definition': 'Sleep leg cramps',
                          'encoding': {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_urinate={'definition': 'Sleep urinate',
                       'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_parasthesia={'definition': 'Sleep parasthesia',
                           'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_heart_pain={'definition': 'Sleep heart pain',
                          'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_itch={'definition': 'Sleep itch',
                    'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_chest_pain={'definition': 'Sleep chest pain',
                         'encoding': {'moderate / sometimes': 2,
                                      'not at all / none': 0,
                                      'often': 3,
                                      'severe / always': 4,
                                      'slight / few times': 1}},
     sa_sleep_shortof_breath={'definition': 'Sleep shortof breath',
                              'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_asthma={'definition': 'Sleep asthma',
                      'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_indigestion={'definition': 'Sleep indigestion',
                           'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_cough={'definition': 'Sleep cough',
                     'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_throat_burn={'definition': 'Sleep throat burn',
                           'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_hunger={'definition': 'Sleep hunger',
                      'encoding':  {'moderate / sometimes': 2,
                                                     'not at all / none': 0,
                                                     'often': 3,
                                                     'severe / always': 4,
                                                     'slight / few times': 1}},
     sa_sleep_alert={'definition': 'Sleep alert',
                      'encoding': {'moderate / sometimes': 2,
                                   'not at all / none': 0,
                                   'often': 3,
                                   'severe / always': 4,
                                   'slight / few times': 1}},
     sa_shift_1st={'definition': 'shift 1st', 'encoding': {'yes': 1, 'no': 0}},
     sa_shift_2nd={'definition': 'shift 2nd', 'encoding': {'yes': 1, 'no': 0}},
     sa_shift_3rd={'definition': 'shift 3rd', 'encoding': {'yes': 1, 'no': 0}},
     sa_shift_swing={'definition': 'shift swing', 'encoding': {'yes': 1, 'no': 0}},
     sa_too_little_sleep={'definition': 'too_little_sleep', 'encoding': {'yes': 1, 'no': 0}},
     sa_too_much_sleep={'definition': 'too_much_sleep', 'encoding': {'yes': 1, 'no': 0}},
     sa_work_sleep_fatique={'definition': 'too_much_sleep', 'encoding': {}},

    sa_accident_sleep_mistakes={'definition': 'accident sleep mistake', 'encoding': {}},
    sa_accident_sleep_fatigue={'definition': 'sleep accident fatigue', 'encoding': {}},
    sa_time_in_bed_weekday_hours={'definition': 'time in beed (weekday)', 'encoding': {}},
    sa_time_in_bed_weekend_hours={'definition': 'time in bed (weekend)', 'encoding': {}},
    # sa_no_of_misses_binary={'definition': 'number of missed accidents', 'encoding': {'yes': 1, 'no': 0}},
    sa_do_you_nap={'definition': 'nap', 'encoding': {'yes': 1, 'no': 0}},

     presleep_physical_complaints_today={'definition': 'physical complaints today',
                                         'encoding': {'yes': 1, 'no': 0}},
     presleep_feel_sleepy_today={'definition': 'feel sleepy today',
                                 'encoding': {'yes': 1, 'no': 0}},
     presleep_outof_ordinary_happen_today={'definition': 'Out of ordinary happen today',
                                           'encoding': {'yes': 1, 'no': 0}},
     presleep_naps_today={'definition': 'naps today',
                          'encoding': {'yes': 1, 'no': 0}},
     presleep_physical_strenuous_day={'definition': 'Physical strenuous day',
                                      'encoding': {'yes': 1, 'no': 0}},
     presleep_medications_today={'definition': 'Medications today',
                                 'encoding': {'yes': 1, 'no': 0}},
     presleep_feel_tired_now={'definition': 'Feel tired now',
                              'encoding':  {'quite a bit': 2,
                                            'not at all / none': 0,
                                            'extreme': 3,
                                            'a little': 1}},
     presleep_medications_past_month={'definition': 'medication past month',
                                      'encoding': {'yes': 1, 'no': 0}},
     presleep_feel_sleepy_now={'definition': 'feel sleepy now',
                               'encoding': {'quite a bit': 2,
                                            'not at all / none': 0,
                                            'extreme': 3,
                                            'a little': 1}},
     presleep_alcohol_beverage_today={'definition': 'alcohol beverage today',
                                      'encoding': {'yes': 1, 'no': 0}},
     presleep_feel_alert_now={'definition': 'feel alert now',
                              'encoding':  {'quite a bit': 2,
                                            'not at all / none': 0,
                                            'extreme': 3,
                                            'a little': 1}},
     presleep_caffeinated_beverage_today={'definition': 'caffeinated beverage today',
                                          'encoding': {'yes': 1, 'no': 0}},
     postsleep_have_difficulty_falling_asleep={'definition': 'Have difficulty falling asleep',
                                               'encoding': {'yes': 1, 'no': 0}},
     postsleep_slept_longer={'definition': 'Slep longer',
                             'encoding': {'yes': 1, 'no': 0}},
     postsleep_wake_during_night={'definition': 'Wake during night',
                                  'encoding': {'yes': 1, 'no': 0}},
     postsleep_awake_feeling={'definition': 'Awake feeling',
                              'encoding': {'better': 1, 'same': 0, 'worse': -1}},
     postsleep_difficulty_goingback_sleep={'definition': 'Difficulty going back sleep',
                                           'encoding': {'yes': 1, 'no': 0}},
     postsleep_feeling_refreshing={'definition': 'Feeling refreshing',
                                   'encoding': {'a little': 1, 'extremely': 3, 'not at all / none': 0,
                                                'quite a bit': 2}},
     postsleep_dreaming_last_night={'definition': 'Dreaming last night',
                                    'encoding': {'yes': 1, 'no': 0}},
     postsleep_feeling_tired={'definition': 'refreshed_questionnaire',
                              'encoding': {'quite a bit': 2,
                                            'not at all / none': 0,
                                            'extreme': 3,
                                            'a little': 1}},
     postsleep_feeling_sleepy={'definition': 'Feeling sleepy',
                               'encoding': {'quite a bit': 2,
                                            'not at all / none': 0,
                                            'extreme': 3,
                                            'a little': 1}},
     postsleep_feeling_alert={'definition': 'Feeling alert',
                              'encoding': {'quite a bit': 2,
                                            'not at all / none': 0,
                                            'extreme': 3,
                                            'a little': 1}},
    postsleep_feeling_sick={'definition': 'Feeling sick',
                            'encoding': {'yes': 1, 'no': 0}},
    postsleep_last_night_sleep_quality={'definition': 'Sleep quality last night',
                                    'encoding': {'yes': 1, 'no': 0}},
    # df={'definition': 'sleep_quality_questionnaire',
    #                                  'encoding': {'less rested': -1, 'more rested than usual': 1, 'same': 0}},
    # awake_feeling_questionnaire={'definition': 'awake_feeling_questionnaire',
    #                           'encoding': {'worse': -1, 'same': 0, 'better': 1}},
    # sleep_quality_questionnaire={'definition': 'sleep_quality_questionnaire',
    #                           'encoding': {'less rested': -1, 'same': 0, 'more rested than usual': 1}},
    # epworth_questionnaire={'definition': 'epworth_questionnaire',
    #                     'encoding': {'would never doze': 0, 'slight chance': 1, 'moderate chance': 2,
    #                                  'high chance of dozing': 3}},
    # refreshed_questionnaire={'definition': 'refreshed_questionnaire',
    #                       'encoding': {'not at all / none': 0, 'a little': 1, 'quite a bit': 2, 'extremely': 3}},
    # anxiety_questionnaire={'definition': 'anxiety_questionnaire',
    #                     'encoding': {'not at all / none': 0, 'slight / few times': 1, 'moderate / sometimes': 2,
    #                                  'often': 3, 'severe / always': 4}},


)
